// <auto-generated />
using System;
using IssueTracker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.Persistence.Migrations
{
    [DbContext(typeof(IssueDbContext))]
    partial class IssueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("IssueTracker.Application.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PriorityId");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Issues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            AssigneeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedUtc = 1308083945472000000L,
                            Description = "Submitting the login form with an empty password returns a 500.",
                            Key = "ISSUE-1",
                            Priority = 1,
                            Status = 1,
                            Title = "Login page throws on empty password",
                            UpdatedUtc = 1308083945472000000L
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            AssigneeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedUtc = 1308083945472000000L,
                            Description = "The dashboard takes several seconds to render for large datasets.",
                            Key = "ISSUE-2",
                            Priority = 2,
                            Status = 2,
                            Title = "Improve dashboard load time",
                            UpdatedUtc = 1308083945472000000L
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            CreatedUtc = 1308083945472000000L,
                            Key = "ISSUE-3",
                            Priority = 4,
                            Status = 1,
                            Title = "Add dark mode toggle",
                            UpdatedUtc = 1308083945472000000L
                        });
                });

            modelBuilder.Entity("IssueTracker.Application.Domain.IssuePriorityRef", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IssuePriorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Critical",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "High",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medium",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Low",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("IssueTracker.Application.Domain.IssueStatusRef", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IssueStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "In Progress",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resolved",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Closed",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("IssueTracker.Application.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedUtc = 1308083945472000000L,
                            Email = "ada@example.com",
                            FirstName = "Ada",
                            LastName = "Lovelace",
                            UpdatedUtc = 1308083945472000000L
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedUtc = 1308083945472000000L,
                            Email = "ben@example.com",
                            FirstName = "Ben",
                            LastName = "Turing",
                            UpdatedUtc = 1308083945472000000L
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedUtc = 1308083945472000000L,
                            Email = "clara@example.com",
                            FirstName = "Clara",
                            LastName = "Hopper",
                            UpdatedUtc = 1308083945472000000L
                        });
                });

            modelBuilder.Entity("IssueTracker.Persistence.Counter", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Counters", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "issue-key",
                            Value = 3L
                        });
                });

            modelBuilder.Entity("IssueTracker.Application.Domain.Issue", b =>
                {
                    b.HasOne("IssueTracker.Application.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IssueTracker.Application.Domain.IssuePriorityRef", null)
                        .WithMany()
                        .HasForeignKey("Priority")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IssueTracker.Application.Domain.IssueStatusRef", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
