<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>IssueTracker.Application</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="D20Tek.Functional" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\D20Tek.Vertically\D20Tek.Vertically.csproj" />
  </ItemGroup>
</Project>
